(define (square x)
  (* x x))
(define (average x y)
  (/ (+ x y)
     2))
(define (abs x)
  (if (>= x 0)
      x
      (- x)))
(define (even? n)
  (= (remainder n 2) 0))
(even? 99)
(define (halve x)
  (/ x 2))
(define (double x)
  (* x 2))
(define (divides? a b)
  (= (remainder b a)
     0))
