;; 定义过程cubic,用牛顿法可以逼近三次方程x^3+ax^2+bx+c的零点
(load (absolute "c01/p49-newton-transform.scm"))
(define (cubic a b c)
  (lambda(x)
    (+ (cube x)
       (* a (square x))
       (* b x)
       c)))
(newton-method (cubic a b c) 1)
(newton-method (cubic 0 0 -1) 1)
(newton-method (cubic 3 2 1) 1)
