(define (timed-prime-test n)
  (display n)
  (start-prime-test n (runtime)))

(define (start-prime-test n start-time)
  (display start-time)
  (if (prime? n)
      (report-prime (- (runtime)
                       start-time))))

(define (report-prime elapsed-time)
  (display "***")
  (newline)
  (display elapsed-time))
(display "***\n")

(define (search-for-primes min)
  (search-for-primes-odd (if (even? min)
                             (+ min 1)
                             min)))
