(load-r "lib/rand-update.scm")
(define random-init 10)
(define rand
  (let ((x random-init))
    (define (generate)
      (set! x (rand-update x))
      x)
    (define (reset new-value)
      (set! x new-value)
      x)
    (define (dispatch arg)
      (cond ((eq? arg 'generate)
	     (generate))
	    ((eq? arg 'reset)
	     reset)
	    (else (error "no such methods"))))
    dispatch))

(rand 'generate)
((rand 'reset) 100)
