(load-r "c02/p99.scm")
;; a.中缀表达式
;; 改前缀运算,为中缀运算
(define (deriv exp var)
  (display exp)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp)
         (make-sum (deriv (addend exp) var)
                   (deriv (augend exp) var)))
        ((product? exp)
         (make-sum
          (make-product (multiplier exp)
                        (deriv (multiplicand exp) var))
          (make-product (deriv (multiplier exp) var)
                        (multiplicand exp))))
        (else
         (error "unknown expression type -- DERIV" exp))))
;; 构造和式make-sum,addend,augend
(define (make-sum x y)
  (list x '+ y))
(define addend car)
(define augend caddr)
(define (sum? s)
  (and (pair? s)
       (eq? (cadr s) '+)))
(define s1 (make-sum 1 2))
(addend s1)
(augend s1)
(sum? s1)

;; product数据抽象:make-product,multiplier,multiplicand 
(define (make-product x y)
  (list x '* y))
(define multiplier car)
(define multiplicand caddr)
(define (product? p)
  (and (pair? p)
       (eq? (cadr p) '*)))
(define p1 (make-product 1 2))
(multiplier p1)
(multiplicand p1)
(product? p1)

(deriv '((x * x) + 3) 'x)

;; b.可以不带括号的中缀表达式
;;   (x + 3 * x + y)
(define (deriv exp var)
  (display exp)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp)
         (make-sum (deriv (addend exp) var)
                   (deriv (augend exp) var)))
        ((product? exp)
         (make-sum
          (make-product (multiplier exp)
                        (deriv (multiplicand exp) var))
          (make-product (deriv (multiplier exp) var)
                        (multiplicand exp))))
        (else
         (error "unknown expression type -- DERIV" exp))))
;; 正确的运算顺序
;;   3 + 4 * x -> (3 + (4 * x))
(define (transfer lst)
  (define (iter incomplete-result result-end remain)
    (if (null? remain)
        (append incomplete-result result-end)
        (if (eq? (car remain) '*)
            (iter incomplete-result (list (list result-end '* (cadr remain))) (cdr (cdr remain)))
            (iter (append incomplete-result (list result-end)) (car remain) (cdr remain)))))
  (iter () (car lst) (cdr lst)))
(transfer '(3 + 4 * x))
