(define (install-=zero?-package)
  (put '=zero? '(scheme-number)
       (lambda (x) (= x 0)))
  (put '=zero? '(rational)
       (lambda (x) (= (numer x) 0)))
  (put '=zero? '(complex)
       (lambda (x) (and (apply-generic '=zero? (real-part x))
                        (apply-generic '=zero? (imag-part x)))))
  (put '=zero? '(polynomial)
       (lambda (x) (apply-generic '=zero? (coeff x))))
  'done)
(define =zero?-package (install-=zero?-package))
