(define (* a b)
  (* a b 0))
(define (* a b s)
  (cond ((= b 0) 0)
        ((even? b)(f (double a)
                     (havle b)
                     s))
        (else (f a
                 (- b 1)
                 (+ s a)))))
