(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))))
(define (devide? a b)
  (= (reminder b a) 0))
(define (prime? n)
  (= n (smallest-divisor n)))

(timed-prime-test 1000)
